/**
 * SCRIPT DE SEED — Menu Pause Café
 * Insère les items du menu en BDD pour avoir du contenu de test.
 *
 * Usage :
 *   npx ts-node src/seed.ts
 *
 * Prérequis : menu-service/.env avec MONGODB_URI configuré
 */

import mongoose from 'mongoose';
import * as dotenv from 'dotenv';

dotenv.config();

const MONGODB_URI =
  process.env.MONGODB_URI || 'mongodb://localhost:27017/menu-db';

const menuItemSchema = new mongoose.Schema({
  name: String,
  description: String,
  price: Number,
  mainCategory: String,
  subCategory: String,
  ingredients: [String],
  allergens: [String],
  available: { type: Boolean, default: true },
  preparationTime: Number,
});

const MenuItemModel = mongoose.model('MenuItem', menuItemSchema);

const menuItems = [
  // ══════════════════════════════════════════════════════════════════════════
  // FOOD
  // ══════════════════════════════════════════════════════════════════════════

  // ── ENTRÉES / ASSIETTES À PARTAGER ───────────────────────────────────────

  {
    name: 'Soupe du jour',
    description:
      "Soupe du jour à l'ardoise, préparée avec des produits frais du marché",
    price: 7,
    mainCategory: 'food',
    subCategory: 'entree',
    ingredients: ['légumes de saison'],
    allergens: [],
    preparationTime: 10,
  },
  {
    name: 'Oeufs pochés bio en cocotte',
    description: 'Oeufs pochés bio en cocotte, ciboulette — avec bacon +1€',
    price: 7,
    mainCategory: 'food',
    subCategory: 'entree',
    ingredients: ['oeufs bio', 'ciboulette', 'crème'],
    allergens: ['oeufs', 'lait'],
    preparationTime: 12,
  },
  {
    name: 'Tarama blanc',
    description: 'Tarama blanc au sumac, servi avec du pain grillé',
    price: 8,
    mainCategory: 'food',
    subCategory: 'entree',
    ingredients: ['tarama', 'sumac', 'pain grillé'],
    allergens: ['poisson', 'gluten'],
    preparationTime: 5,
  },
  {
    name: 'Houmous',
    description: "Houmous, huile au piment d'Alep, pita maison (V)",
    price: 8,
    mainCategory: 'food',
    subCategory: 'entree',
    ingredients: ['pois chiches', 'tahini', "piment d'Alep", 'pita maison'],
    allergens: ['gluten', 'sésame'],
    preparationTime: 5,
  },
  {
    name: 'Falafels',
    description: 'Falafels, sauce yaourt citron / tahini (V)',
    price: 8,
    mainCategory: 'food',
    subCategory: 'entree',
    ingredients: ['pois chiches', 'herbes', 'yaourt', 'citron', 'tahini'],
    allergens: ['sésame', 'lait'],
    preparationTime: 8,
  },
  {
    name: 'Straciatella',
    description:
      'Straciatella, huile vierge, poires rôties, romarin et pain grillé (V)',
    price: 10,
    mainCategory: 'food',
    subCategory: 'entree',
    ingredients: ['straciatella', 'poires', 'romarin', 'pain grillé'],
    allergens: ['lait', 'gluten'],
    preparationTime: 8,
  },

  // ── TAPAS ─────────────────────────────────────────────────────────────────

  {
    name: 'Accras de cabillaud',
    description: 'Accras de cabillaud, sweet chili sauce',
    price: 9,
    mainCategory: 'food',
    subCategory: 'tapas',
    ingredients: ['cabillaud', 'farine', 'sweet chili'],
    allergens: ['poisson', 'gluten'],
    preparationTime: 10,
  },
  {
    name: 'Calamars frits',
    description: 'Calamars frits, sauce jalapeño ranch',
    price: 9,
    mainCategory: 'food',
    subCategory: 'tapas',
    ingredients: ['calamars', 'farine', 'jalapeño', 'ranch'],
    allergens: ['gluten', 'lait', 'mollusques'],
    preparationTime: 10,
  },
  {
    name: 'Croquetas de chorizo',
    description: 'Croquetas de chorizo, croustillantes et dorées',
    price: 9,
    mainCategory: 'food',
    subCategory: 'tapas',
    ingredients: ['chorizo', 'béchamel', 'chapelure'],
    allergens: ['gluten', 'lait'],
    preparationTime: 10,
  },
  {
    name: 'Assiette de charcuterie',
    description:
      'Assiette de charcuterie de la Maison "MAS" — jambon de pays, coppa, chorizo, saucisson sec',
    price: 17,
    mainCategory: 'food',
    subCategory: 'tapas',
    ingredients: ['jambon de pays', 'coppa', 'chorizo', 'saucisson sec'],
    allergens: [],
    preparationTime: 5,
  },
  {
    name: 'Combo charcuterie + fromages',
    description:
      'Combo charcuterie + Comté affiné 18 mois + Saint Nectaire fermier',
    price: 20,
    mainCategory: 'food',
    subCategory: 'tapas',
    ingredients: ['charcuterie MAS', 'Comté 18 mois', 'Saint Nectaire fermier'],
    allergens: ['lait'],
    preparationTime: 5,
  },

  // ── SALADES / PLATS ───────────────────────────────────────────────────────

  {
    name: 'Salade chinoise',
    description: 'Poulet snacké, maki au concombre, Shangaï sauce',
    price: 15,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: ['poulet', 'concombre', 'riz', 'sauce Shangaï'],
    allergens: ['gluten', 'soja'],
    preparationTime: 15,
  },
  {
    name: 'Chirachi bowl saumon',
    description: 'Saumon Label Rouge, riz vinaigré, avocat & sauce ponzu',
    price: 16.5,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: [
      'saumon Label Rouge',
      'riz vinaigré',
      'avocat',
      'sauce ponzu',
    ],
    allergens: ['poisson', 'soja', 'gluten'],
    preparationTime: 15,
  },
  {
    name: 'Salade avocat quinoa halloumi',
    description: 'Salade avocat, quinoa, halloumi rôti aux herbes (V)',
    price: 15,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: ['avocat', 'quinoa', 'halloumi', 'herbes'],
    allergens: ['lait'],
    preparationTime: 15,
  },
  {
    name: 'Salade avocat quinoa poulet',
    description:
      "Salade avocat, quinoa, poulet mariné au miel d'épices & sésame",
    price: 15,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: ['avocat', 'quinoa', 'poulet', 'miel', 'sésame'],
    allergens: ['sésame'],
    preparationTime: 15,
  },
  {
    name: 'Orecchiette pesto pistache',
    description: 'Orecchiette, pesto de pistache & basilic, parmesan (V)',
    price: 14,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: ['orecchiette', 'pistache', 'basilic', 'parmesan'],
    allergens: ['gluten', 'lait', 'fruits à coque'],
    preparationTime: 20,
  },
  {
    name: 'Dahl de lentilles',
    description: 'Dahl de lentilles, riz du dragon (V)',
    price: 14,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: ['lentilles', 'riz du dragon', 'épices'],
    allergens: [],
    preparationTime: 20,
  },
  {
    name: 'Lasagnes de légumes',
    description:
      'Lasagnes de légumes, aubergines, courgettes, sauce tomate et roquette (V)',
    price: 15,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: [
      'aubergines',
      'courgettes',
      'sauce tomate',
      'roquette',
      'pâtes',
    ],
    allergens: ['gluten', 'lait'],
    preparationTime: 25,
  },
  {
    name: 'Veggie burger',
    description:
      'Veggie burger, halloumi, portobello et frites de patates douces (V)',
    price: 15,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: ['halloumi', 'portobello', 'patates douces', 'bun'],
    allergens: ['gluten', 'lait'],
    preparationTime: 20,
  },
  {
    name: 'Saumon laqué teriyaki',
    description:
      'Saumon laqué teriyaki Label Rouge, sauce sriracha & riz du dragon',
    price: 18,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: [
      'saumon Label Rouge',
      'sauce teriyaki',
      'sriracha',
      'riz du dragon',
    ],
    allergens: ['poisson', 'soja', 'gluten'],
    preparationTime: 20,
  },
  {
    name: 'Thon albacore mi-cuit',
    description: 'Thon albacore mi-cuit, sauce sésame, aubergines Hong Shao',
    price: 21,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: ['thon albacore', 'sauce sésame', 'aubergines'],
    allergens: ['poisson', 'sésame', 'soja'],
    preparationTime: 20,
  },
  {
    name: 'Satay de volaille',
    description: 'Satay de volaille, nouilles chinoises et légumes sautés',
    price: 15,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: ['volaille', 'nouilles chinoises', 'légumes', 'sauce satay'],
    allergens: ['gluten', 'soja', 'arachides'],
    preparationTime: 20,
  },
  {
    name: 'Poulet crousti-crousti',
    description: 'Poulet crousti-crousti, purée maison, sweet chili sauce',
    price: 15,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: ['poulet', 'purée maison', 'sweet chili sauce'],
    allergens: ['gluten', 'lait'],
    preparationTime: 25,
  },
  {
    name: 'Tartare de boeuf',
    description: 'Tartare de bœuf à notre façon, servi avec frites maison',
    price: 16,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: ['bœuf', 'câpres', 'échalotes', 'cornichons', 'frites maison'],
    allergens: ['oeufs', 'moutarde'],
    preparationTime: 15,
  },
  {
    name: 'Pavé de boeuf béarnaise',
    description: 'Pavé de bœuf sauce béarnaise, servi avec frites maison',
    price: 18,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: ['bœuf', 'sauce béarnaise', 'frites maison'],
    allergens: ['oeufs', 'lait'],
    preparationTime: 20,
  },
  {
    name: 'Cheese burger',
    description:
      'Potatoe bun, cheddar affiné 9 mois, oignons confits, sauce secrète, frites maison',
    price: 16,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: [
      'bœuf',
      'potatoe bun',
      'cheddar 9 mois',
      'oignons confits',
      'sauce secrète',
    ],
    allergens: ['gluten', 'lait', 'oeufs'],
    preparationTime: 20,
  },
  {
    name: 'Bacon cheese burger',
    description:
      'Cheddar affiné 9 mois, oignons confits, sauce secrète & bacon, frites maison',
    price: 17.5,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: [
      'bœuf',
      'bacon',
      'cheddar 9 mois',
      'oignons confits',
      'sauce secrète',
    ],
    allergens: ['gluten', 'lait', 'oeufs'],
    preparationTime: 20,
  },
  {
    name: 'Pork bun',
    description:
      'Effiloché de porc fumé, coleslaw de chou rouge, sauce spicy BBQ, frites maison',
    price: 16,
    mainCategory: 'food',
    subCategory: 'plat',
    ingredients: ['porc fumé effiloché', 'chou rouge', 'sauce BBQ', 'bun'],
    allergens: ['gluten', 'lait'],
    preparationTime: 20,
  },

  // ── SIDES ─────────────────────────────────────────────────────────────────

  {
    name: 'Frites homemade',
    description: 'Frites maison cuites en 2 cuissons',
    price: 5,
    mainCategory: 'food',
    subCategory: 'side',
    ingredients: ['pommes de terre'],
    allergens: [],
    preparationTime: 15,
  },
  {
    name: 'Purée maison',
    description: 'Purée maison, beurre et lait frais',
    price: 5,
    mainCategory: 'food',
    subCategory: 'side',
    ingredients: ['pommes de terre', 'beurre', 'lait'],
    allergens: ['lait'],
    preparationTime: 10,
  },
  {
    name: 'Sweet potatoes',
    description: 'Frites de patates douces',
    price: 6,
    mainCategory: 'food',
    subCategory: 'side',
    ingredients: ['patates douces'],
    allergens: [],
    preparationTime: 15,
  },
  {
    name: 'Aubergines Hong Shao',
    description: 'Aubergines mijotées à la façon Hong Shao',
    price: 7,
    mainCategory: 'food',
    subCategory: 'side',
    ingredients: ['aubergines', 'sauce soja', 'gingembre', 'ail'],
    allergens: ['soja'],
    preparationTime: 20,
  },

  // ── DESSERTS ──────────────────────────────────────────────────────────────

  {
    name: 'Cookie choco-noisettes',
    description: 'Cookie choco-noisettes, moelleux et généreux',
    price: 4,
    mainCategory: 'food',
    subCategory: 'dessert',
    ingredients: ['chocolat', 'noisettes', 'farine', 'beurre'],
    allergens: ['gluten', 'lait', 'fruits à coque', 'oeufs'],
    preparationTime: 5,
  },
  {
    name: 'Cookie + café',
    description: "Cookie choco-noisettes accompagné d'un café",
    price: 6,
    mainCategory: 'food',
    subCategory: 'dessert',
    ingredients: ['cookie', 'café'],
    allergens: ['gluten', 'lait', 'fruits à coque', 'oeufs'],
    preparationTime: 5,
  },
  {
    name: 'Tiramisù',
    description: 'Tiramisù maison, mascarpone, biscuits cuillère, café',
    price: 7,
    mainCategory: 'food',
    subCategory: 'dessert',
    ingredients: ['mascarpone', 'biscuits cuillère', 'café', 'oeufs'],
    allergens: ['lait', 'gluten', 'oeufs'],
    preparationTime: 5,
  },
  {
    name: 'Gâteau choco',
    description: 'Gâteau au chocolat maison, fondant et intense',
    price: 7,
    mainCategory: 'food',
    subCategory: 'dessert',
    ingredients: ['chocolat noir', 'beurre', 'oeufs', 'farine'],
    allergens: ['gluten', 'lait', 'oeufs'],
    preparationTime: 5,
  },
  {
    name: 'Fromage blanc coulis',
    description: 'Fromage blanc, coulis de fruits rouges',
    price: 6,
    mainCategory: 'food',
    subCategory: 'dessert',
    ingredients: ['fromage blanc', 'coulis de fruits rouges'],
    allergens: ['lait'],
    preparationTime: 5,
  },
  {
    name: 'Riz au lait vanillé',
    description: 'Riz au lait vanillé, caramel beurre salé, spéculoos',
    price: 7,
    mainCategory: 'food',
    subCategory: 'dessert',
    ingredients: ['riz', 'lait', 'vanille', 'caramel beurre salé', 'spéculoos'],
    allergens: ['lait', 'gluten'],
    preparationTime: 5,
  },
  {
    name: 'Cheese cake',
    description: 'Cheese cake maison, coulis de fruits rouges',
    price: 7,
    mainCategory: 'food',
    subCategory: 'dessert',
    ingredients: ['cream cheese', 'biscuits', 'coulis'],
    allergens: ['lait', 'gluten', 'oeufs'],
    preparationTime: 5,
  },
  {
    name: 'Comté affiné 18 mois',
    description: 'Comté affiné 18 mois et/ou Saint Nectaire fermier',
    price: 8,
    mainCategory: 'food',
    subCategory: 'dessert',
    ingredients: ['Comté 18 mois', 'Saint Nectaire fermier'],
    allergens: ['lait'],
    preparationTime: 5,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // DRINKS
  // ══════════════════════════════════════════════════════════════════════════

  // ── VINS BLANCS ───────────────────────────────────────────────────────────

  {
    name: 'Côteaux de Vendômois — Verre 12.5cl',
    description: 'Domaine du Four à Chaux — Chenin, culture raisonnée',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['chenin'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Côteaux de Vendômois — 35cl',
    description: 'Domaine du Four à Chaux — Chenin, culture raisonnée',
    price: 11,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['chenin'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Côteaux de Vendômois — Bouteille',
    description: 'Domaine du Four à Chaux — Chenin, culture raisonnée',
    price: 22,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['chenin'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Chardonnay — Verre 12.5cl',
    description: 'Ailleurs Chardonnay — Domaine Attilon, BIO',
    price: 6.5,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['chardonnay'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Chardonnay — 35cl',
    description: 'Ailleurs Chardonnay — Domaine Attilon, BIO',
    price: 14,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['chardonnay'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Chardonnay — Bouteille',
    description: 'Ailleurs Chardonnay — Domaine Attilon, BIO',
    price: 28,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['chardonnay'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Pépin Blanc — Verre 12.5cl',
    description: 'Vin nature non filtré — Alsace Vin de France',
    price: 7,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['raisins blancs'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Pépin Blanc — 35cl',
    description: 'Vin nature non filtré — Alsace Vin de France',
    price: 15,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['raisins blancs'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Pépin Blanc — Bouteille',
    description: 'Vin nature non filtré — Alsace Vin de France',
    price: 30,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['raisins blancs'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Menetou-Salon — Verre 12.5cl',
    description: 'Remoortere — Sauvignon BIO',
    price: 8,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['sauvignon'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Menetou-Salon — 35cl',
    description: 'Remoortere — Sauvignon BIO',
    price: 17,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['sauvignon'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Menetou-Salon — Bouteille',
    description: 'Remoortere — Sauvignon BIO',
    price: 34,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['sauvignon'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },

  // ── VINS ROSÉS ────────────────────────────────────────────────────────────

  {
    name: 'Gris de Nathalie — Verre 12.5cl',
    description: 'Domaine du Petit Chaumont — IGP Sable de Camargue, BIO',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['grenache', 'syrah'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Gris de Nathalie — 35cl',
    description: 'Domaine du Petit Chaumont — IGP Sable de Camargue, BIO',
    price: 11,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['grenache', 'syrah'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Gris de Nathalie — Bouteille',
    description: 'Domaine du Petit Chaumont — IGP Sable de Camargue, BIO',
    price: 22,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['grenache', 'syrah'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Côtes de Provence — Bouteille',
    description: 'Symphonie — Château Sainte Marguerite, Cru Classé BIO',
    price: 32,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['grenache', 'cinsault', 'rolle'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },

  // ── VINS ORANGE ───────────────────────────────────────────────────────────

  {
    name: 'Pépin Orange — Verre 12.5cl',
    description: 'Biodynamie, sans sulfite — Alsace Vin de France',
    price: 7,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['raisins orange'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Pépin Orange — 35cl',
    description: 'Biodynamie, sans sulfite — Alsace Vin de France',
    price: 15,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['raisins orange'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Pépin Orange — Bouteille',
    description: 'Biodynamie, sans sulfite — Alsace Vin de France',
    price: 30,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['raisins orange'],
    allergens: [],
    preparationTime: 2,
  },

  // ── VINS ROUGES ───────────────────────────────────────────────────────────

  {
    name: 'Côtes de Bordeaux — Verre 12.5cl',
    description: 'Pirouette — Château Les Vieux Moulins, BIO',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['merlot', 'cabernet'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Côtes de Bordeaux — 35cl',
    description: 'Pirouette — Château Les Vieux Moulins, BIO',
    price: 11,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['merlot', 'cabernet'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Côtes de Bordeaux — Bouteille',
    description: 'Pirouette — Château Les Vieux Moulins, BIO',
    price: 22,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['merlot', 'cabernet'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Côtes du Rhône — Verre 12.5cl',
    description: 'Bourdon — Domaine de Pieblanc, conversion BIO',
    price: 6.5,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['grenache', 'syrah'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Côtes du Rhône — 35cl',
    description: 'Bourdon — Domaine de Pieblanc, conversion BIO',
    price: 14,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['grenache', 'syrah'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Côtes du Rhône — Bouteille',
    description: 'Bourdon — Domaine de Pieblanc, conversion BIO',
    price: 28,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['grenache', 'syrah'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Bourgueil — Verre 12.5cl',
    description: 'Trinch — Catherine & Pierre Breton, BIO',
    price: 7,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['cabernet franc'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Bourgueil — 35cl',
    description: 'Trinch — Catherine & Pierre Breton, BIO',
    price: 15,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['cabernet franc'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Bourgueil — Bouteille',
    description: 'Trinch — Catherine & Pierre Breton, BIO',
    price: 30,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['cabernet franc'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Côte-Roannaise Gamay — Verre 12.5cl',
    description: 'Éclat de Granite — Domaine Sérol, BIO',
    price: 7,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['gamay'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Côte-Roannaise Gamay — 35cl',
    description: 'Éclat de Granite — Domaine Sérol, BIO',
    price: 15,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['gamay'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Côte-Roannaise Gamay — Bouteille',
    description: 'Éclat de Granite — Domaine Sérol, BIO',
    price: 30,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['gamay'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Cahors Malbec — Bouteille',
    description: 'Nucôt — Clos Dauriac, biodynamie',
    price: 32,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['malbec'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Bourgogne Pinot Noir — Bouteille',
    description: "Les Fôrets Rouges — L'Oeuvre de Perraud, culture raisonnée",
    price: 35,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['pinot noir'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Pic-Saint-Loup — Bouteille',
    description: "L'Orphée — Mas Foulaquier, biodynamie",
    price: 39,
    mainCategory: 'drinks',
    subCategory: 'vin',
    ingredients: ['syrah', 'grenache'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },

  // ── BULLES ────────────────────────────────────────────────────────────────

  {
    name: 'Vouvray brut pétillant — Verre 12cl',
    description: 'La Dilettante — Catherine & Pierre Breton, BIO',
    price: 8,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['chenin'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Vouvray brut pétillant — Bouteille',
    description: 'La Dilettante — Catherine & Pierre Breton, BIO',
    price: 32,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['chenin'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Champagne Laurent Perrier — Verre 12cl',
    description: 'La Cuvée — culture raisonnée',
    price: 12,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['chardonnay', 'pinot noir', 'pinot meunier'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Champagne Laurent Perrier — Bouteille',
    description: 'La Cuvée — culture raisonnée',
    price: 72,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['chardonnay', 'pinot noir', 'pinot meunier'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },

  // ── BIÈRES PRESSION ───────────────────────────────────────────────────────

  {
    name: 'Stella Artois — 25cl',
    description: 'Stella Artois pression',
    price: 4,
    mainCategory: 'drinks',
    subCategory: 'biere',
    ingredients: ["malt d'orge", 'houblon', 'eau', 'levure'],
    allergens: ['gluten'],
    preparationTime: 2,
  },
  {
    name: 'Stella Artois — Pinte 50cl',
    description: 'Stella Artois pression',
    price: 6.5,
    mainCategory: 'drinks',
    subCategory: 'biere',
    ingredients: ["malt d'orge", 'houblon', 'eau', 'levure'],
    allergens: ['gluten'],
    preparationTime: 2,
  },
  {
    name: 'Deck & Donohue Mission Pale Ale — 25cl',
    description: 'Pale Ale BIO artisanale en pression',
    price: 4.8,
    mainCategory: 'drinks',
    subCategory: 'biere',
    ingredients: ['malt', 'houblon', 'eau', 'levure'],
    allergens: ['gluten'],
    preparationTime: 2,
  },
  {
    name: 'Deck & Donohue Mission Pale Ale — Pinte 50cl',
    description: 'Pale Ale BIO artisanale en pression',
    price: 8.5,
    mainCategory: 'drinks',
    subCategory: 'biere',
    ingredients: ['malt', 'houblon', 'eau', 'levure'],
    allergens: ['gluten'],
    preparationTime: 2,
  },
  {
    name: 'Demory Blanche — 25cl',
    description: 'Bière blanche Demory pression',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'biere',
    ingredients: ['malt de blé', 'houblon', 'coriandre', "écorce d'orange"],
    allergens: ['gluten'],
    preparationTime: 2,
  },
  {
    name: 'Demory Blanche — Pinte 50cl',
    description: 'Bière blanche Demory pression',
    price: 9,
    mainCategory: 'drinks',
    subCategory: 'biere',
    ingredients: ['malt de blé', 'houblon', 'coriandre', "écorce d'orange"],
    allergens: ['gluten'],
    preparationTime: 2,
  },
  {
    name: 'Brewdog Punk IPA — 25cl',
    description: 'India Pale Ale Brewdog pression',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'biere',
    ingredients: ['malt', 'houblon Citra', 'eau', 'levure'],
    allergens: ['gluten'],
    preparationTime: 2,
  },
  {
    name: 'Brewdog Punk IPA — Pinte 50cl',
    description: 'India Pale Ale Brewdog pression',
    price: 9,
    mainCategory: 'drinks',
    subCategory: 'biere',
    ingredients: ['malt', 'houblon Citra', 'eau', 'levure'],
    allergens: ['gluten'],
    preparationTime: 2,
  },

  // ── BIÈRES BOUTEILLES ─────────────────────────────────────────────────────

  {
    name: 'Corona',
    description: 'Corona bouteille 33cl',
    price: 6.5,
    mainCategory: 'drinks',
    subCategory: 'biere',
    ingredients: ["malt d'orge", 'houblon', 'maïs', 'eau'],
    allergens: ['gluten'],
    preparationTime: 1,
  },
  {
    name: 'Corona 0.0%',
    description: 'Corona sans alcool bouteille 33cl',
    price: 6.5,
    mainCategory: 'drinks',
    subCategory: 'biere',
    ingredients: ["malt d'orge", 'houblon', 'maïs', 'eau'],
    allergens: ['gluten'],
    preparationTime: 1,
  },
  {
    name: 'Cidre Sassy',
    description: 'Cidre Sassy bouteille 33cl',
    price: 6.5,
    mainCategory: 'drinks',
    subCategory: 'biere',
    ingredients: ['pommes normandes'],
    allergens: [],
    preparationTime: 1,
  },

  // ── SOFTS ─────────────────────────────────────────────────────────────────

  {
    name: 'Coca-Cola',
    description: 'Coca-Cola 33cl',
    price: 4.5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['eau gazéifiée', 'sucre', 'caramel'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Coca Zéro',
    description: 'Coca-Cola Zéro 33cl',
    price: 4.5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['eau gazéifiée', 'édulcorant'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Perrier',
    description: 'Perrier 33cl',
    price: 4.5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['eau gazeuse naturelle'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Ginger Beer Fever Tree',
    description: 'Ginger Beer Fever Tree 20cl — piquante et rafraîchissante',
    price: 4.5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['eau gazeuse', 'gingembre', 'sucre de canne'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Tonic Water Fever Tree',
    description: 'Tonic Water Fever Tree 20cl',
    price: 4.5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['eau gazeuse', 'quinine', 'sucre de canne'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Club-Mate',
    description: 'Club-Mate 33cl — boisson énergisante à base de maté',
    price: 7,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['extrait de maté', 'eau gazeuse', 'sucre'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Kombucha Figuier BIO',
    description: 'Kombucha Figuier BIO Archipel 33cl',
    price: 7,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['thé', 'sucre', 'figue', 'culture SCOBY'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Kombucha Cassis BIO',
    description: 'Kombucha Cassis BIO Archipel 33cl',
    price: 7,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['thé', 'sucre', 'cassis', 'culture SCOBY'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Limonade à la pression',
    description: 'Limonade maison à la pression 33cl',
    price: 3.5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['eau gazeuse', 'citron', 'sucre'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Diabolo',
    description: 'Diabolo menthe, fraise ou grenadine 33cl',
    price: 3.5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['limonade', 'sirop'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Eau minérale + sirop',
    description: 'Eau minérale avec sirop au choix 33cl',
    price: 3.5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['eau minérale', 'sirop'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Thé glacé maison',
    description: 'Thé glacé maison 33cl',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['thé', 'sucre', 'citron'],
    allergens: [],
    preparationTime: 3,
  },
  {
    name: 'Citronnade maison',
    description: 'Citronnade maison pressée 33cl',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['citrons pressés', 'eau', 'sucre de canne'],
    allergens: [],
    preparationTime: 3,
  },
  {
    name: 'Abatilles plate',
    description: 'Eau minérale Abatilles plate 75cl',
    price: 6.5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['eau minérale naturelle'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Abatilles gazeuse',
    description: 'Eau minérale Abatilles gazeuse 75cl',
    price: 6.5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['eau minérale naturelle gazéifiée'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Orange pressée',
    description: "Jus d'orange fraîchement pressé",
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['oranges fraîches'],
    allergens: [],
    preparationTime: 5,
  },
  {
    name: 'Citron pressé',
    description: 'Citron fraîchement pressé',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['citrons frais'],
    allergens: [],
    preparationTime: 5,
  },
  {
    name: 'Jus Abricot Alain Milliat',
    description: "Nectar d'abricot Alain Milliat 20cl",
    price: 6,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['abricots sélectionnés'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Jus Pêche de vigne Alain Milliat',
    description: 'Nectar de pêche de vigne Alain Milliat 20cl',
    price: 6,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['pêches de vigne sélectionnées'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: "Jus Pomme Cox's Alain Milliat",
    description: "Jus de pomme Cox's Alain Milliat 20cl",
    price: 6,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ["pommes Cox's sélectionnées"],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Jus Poire Alain Milliat',
    description: 'Nectar de poire Alain Milliat 20cl',
    price: 6,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['poires sélectionnées'],
    allergens: [],
    preparationTime: 1,
  },
  {
    name: 'Tomate à la verse',
    description: 'Jus de tomate à la verse 35cl',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['jus de tomate'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Café frappé',
    description: 'Café frappé servi glacé',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['café', 'glace'],
    allergens: [],
    preparationTime: 4,
  },
  {
    name: 'Café latte frappé',
    description: 'Café latte frappé servi glacé',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['café', 'lait', 'glace'],
    allergens: ['lait'],
    preparationTime: 4,
  },
  {
    name: 'Iced Chaï latte',
    description: "Iced Chaï latte au lait d'avoine by La Main Noire",
    price: 6,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['chaï', "lait d'avoine", 'glace'],
    allergens: ['avoine'],
    preparationTime: 4,
  },
  {
    name: 'Iced Matcha latte',
    description: "Iced Matcha latte au lait d'avoine by La Main Noire",
    price: 6,
    mainCategory: 'drinks',
    subCategory: 'soft',
    ingredients: ['matcha', "lait d'avoine", 'glace'],
    allergens: ['avoine'],
    preparationTime: 4,
  },

  // ── MOCKTAILS ─────────────────────────────────────────────────────────────

  {
    name: 'Tiki Boubou',
    description: 'Mocktail — crème de coco, tonka, ananas, orange, citron vert',
    price: 7,
    mainCategory: 'drinks',
    subCategory: 'mocktail',
    ingredients: ['crème de coco', 'tonka', 'ananas', 'orange', 'citron vert'],
    allergens: [],
    preparationTime: 5,
  },
  {
    name: 'Ginger Mojito',
    description: 'Mocktail — ginger beer, menthe, citron vert, sucre',
    price: 7,
    mainCategory: 'drinks',
    subCategory: 'mocktail',
    ingredients: ['ginger beer', 'menthe fraîche', 'citron vert', 'sucre'],
    allergens: [],
    preparationTime: 5,
  },

  // ── BOISSONS CHAUDES ──────────────────────────────────────────────────────

  {
    name: 'Café',
    description: 'Café espresso BIO',
    price: 2.2,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['café BIO'],
    allergens: [],
    preparationTime: 3,
  },
  {
    name: 'Café allongé',
    description: 'Café allongé BIO',
    price: 2.2,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['café BIO', 'eau'],
    allergens: [],
    preparationTime: 3,
  },
  {
    name: 'Double café',
    description: 'Double espresso BIO',
    price: 4,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['café BIO'],
    allergens: [],
    preparationTime: 3,
  },
  {
    name: 'Café crème',
    description: 'Café crème BIO',
    price: 4,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['café BIO', 'lait'],
    allergens: ['lait'],
    preparationTime: 3,
  },
  {
    name: 'Chocolat chaud',
    description: 'Chocolat chaud maison',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['cacao', 'lait'],
    allergens: ['lait'],
    preparationTime: 4,
  },
  {
    name: 'Chocolat viennois',
    description: 'Chocolat viennois avec chantilly',
    price: 6,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['chocolat', 'lait', 'chantilly'],
    allergens: ['lait'],
    preparationTime: 4,
  },
  {
    name: 'Café viennois',
    description: 'Café viennois avec chantilly',
    price: 6,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['café', 'chantilly'],
    allergens: ['lait'],
    preparationTime: 4,
  },
  {
    name: 'Cappuccino',
    description: "Cappuccino — supplément lait d'avoine +0.50€",
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['café', 'lait'],
    allergens: ['lait'],
    preparationTime: 4,
  },
  {
    name: 'Café mocha',
    description: "Café mocha — supplément lait d'avoine +0.50€",
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['café', 'chocolat', 'lait'],
    allergens: ['lait'],
    preparationTime: 4,
  },
  {
    name: 'Matcha latte',
    description: "Matcha latte by La Main Noire au lait d'avoine",
    price: 6,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['matcha', "lait d'avoine"],
    allergens: ['avoine'],
    preparationTime: 4,
  },
  {
    name: 'Chaï latte',
    description: "Chaï latte by La Main Noire au lait d'avoine",
    price: 6,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['chaï', "lait d'avoine", 'épices'],
    allergens: ['avoine'],
    preparationTime: 4,
  },
  {
    name: 'Dirty Chaï latte',
    description: 'Dirty Chaï latte — Chaï latte + café',
    price: 6.5,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['chaï', 'café', "lait d'avoine"],
    allergens: ['avoine'],
    preparationTime: 4,
  },
  {
    name: 'Irish Coffee',
    description: 'Irish Coffee au Jameson, crème fouettée',
    price: 10,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['café', 'Jameson', 'crème fouettée', 'sucre'],
    allergens: ['lait'],
    preparationTime: 5,
  },
  {
    name: 'Vin chaud',
    description: 'Vin chaud cannelle, sucre de canne et orange',
    price: 7,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['vin rouge', 'cannelle', 'sucre de canne', 'orange'],
    allergens: ['sulfites'],
    preparationTime: 5,
  },
  {
    name: 'Grog',
    description: 'Grog rhum, miel, gingembre, citron',
    price: 8,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['rhum', 'miel', 'gingembre', 'citron', 'eau chaude'],
    allergens: [],
    preparationTime: 5,
  },
  {
    name: 'Thés noirs Earl Grey',
    description: 'Thé Earl Grey Mariages Frères',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['thé noir Earl Grey'],
    allergens: [],
    preparationTime: 4,
  },
  {
    name: 'Thé Marco Polo',
    description: 'Thé Marco Polo Mariages Frères',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['thé Marco Polo'],
    allergens: [],
    preparationTime: 4,
  },
  {
    name: 'Thé Darjeeling Himalaya',
    description: 'Thé Darjeeling Himalaya Mariages Frères',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['thé Darjeeling'],
    allergens: [],
    preparationTime: 4,
  },
  {
    name: 'Thé vert Fujiyama',
    description: 'Thé vert Fujiyama Mariages Frères',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['thé vert Fujiyama'],
    allergens: [],
    preparationTime: 4,
  },
  {
    name: 'Thé Jasmin Mandarin',
    description: 'Thé Jasmin Mandarin Mariages Frères',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['thé vert', 'jasmin'],
    allergens: [],
    preparationTime: 4,
  },
  {
    name: 'Rooïbos Rouge Métis',
    description: 'Rooïbos Rouge Métis Mariages Frères',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['rooïbos'],
    allergens: [],
    preparationTime: 4,
  },
  {
    name: 'Dream Tea',
    description: 'Infusion de 8 plantes aromatiques Mariages Frères',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['plantes aromatiques'],
    allergens: [],
    preparationTime: 4,
  },
  {
    name: 'Thé vert à la menthe fraîche',
    description: 'Thé vert infusé à la menthe fraîche',
    price: 5.3,
    mainCategory: 'drinks',
    subCategory: 'hot',
    ingredients: ['thé vert', 'menthe fraîche'],
    allergens: [],
    preparationTime: 4,
  },

  // ── APÉRITIFS ─────────────────────────────────────────────────────────────

  {
    name: 'Kir pêche',
    description: 'Kir à la pêche',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['vin blanc', 'liqueur de pêche'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Kir mûre',
    description: 'Kir à la mûre',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['vin blanc', 'liqueur de mûre'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Kir framboise',
    description: 'Kir à la framboise',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['vin blanc', 'liqueur de framboise'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Kir cassis',
    description: 'Kir au cassis',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['vin blanc', 'liqueur de cassis'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Kir cerise',
    description: 'Kir à la cerise',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['vin blanc', 'liqueur de cerise'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Ricard',
    description: 'Ricard, servi avec eau fraîche',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['pastis', 'eau'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Suze',
    description: 'Suze, liqueur de gentiane',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['gentiane', 'alcool'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Campari',
    description: 'Campari servi avec glaçons',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['Campari'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Aperol',
    description: 'Aperol servi avec glaçons',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['Aperol'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Martini Rosso',
    description: 'Martini Rosso servi avec glaçons',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['vermouth rouge'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Martini Bianco',
    description: 'Martini Bianco servi avec glaçons',
    price: 5,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['vermouth blanc'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: "Vermouth Otto's",
    description: "Vermouth Otto's artisanal",
    price: 6,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['vermouth', 'herbes aromatiques'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Aperol Spritz',
    description: 'Aperol, Vouvray pétillant, eau gazeuse',
    price: 9,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['Aperol', 'Vouvray pétillant', 'eau gazeuse', 'orange'],
    allergens: ['sulfites'],
    preparationTime: 3,
  },
  {
    name: 'Campari Spritz',
    description: 'Campari, Vouvray pétillant, eau gazeuse',
    price: 9,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['Campari', 'Vouvray pétillant', 'eau gazeuse'],
    allergens: ['sulfites'],
    preparationTime: 3,
  },
  {
    name: 'Elderflower Spritz',
    description: 'Liqueur de sureau, Vouvray pétillant, eau gazeuse',
    price: 9,
    mainCategory: 'drinks',
    subCategory: 'aperitif',
    ingredients: ['liqueur de sureau', 'Vouvray pétillant', 'eau gazeuse'],
    allergens: ['sulfites'],
    preparationTime: 3,
  },

  // ── COCKTAILS ─────────────────────────────────────────────────────────────

  {
    name: 'Bramble',
    description: 'London dry gin, crème de mûre, citron vert, simple sirop',
    price: 10,
    mainCategory: 'drinks',
    subCategory: 'cocktail',
    ingredients: ['London dry gin', 'crème de mûre', 'citron vert', 'sirop'],
    allergens: [],
    preparationTime: 5,
  },
  {
    name: 'Basil Smash',
    description: 'London dry gin, basilic, citron vert, simple sirop',
    price: 10,
    mainCategory: 'drinks',
    subCategory: 'cocktail',
    ingredients: ['London dry gin', 'basilic frais', 'citron vert', 'sirop'],
    allergens: [],
    preparationTime: 5,
  },
  {
    name: 'Last Word',
    description:
      'London dry gin, Chartreuse, liqueur de marasquin, citron vert',
    price: 12,
    mainCategory: 'drinks',
    subCategory: 'cocktail',
    ingredients: ['London dry gin', 'Chartreuse', 'marasquin', 'citron vert'],
    allergens: [],
    preparationTime: 5,
  },
  {
    name: 'Pistachio Sour',
    description:
      "Gin, Cointreau, orgeat de pistache maison, citron vert, vanille & blanc d'oeuf",
    price: 12,
    mainCategory: 'drinks',
    subCategory: 'cocktail',
    ingredients: [
      'gin',
      'Cointreau',
      'orgeat pistache',
      'citron vert',
      'vanille',
      "blanc d'oeuf",
    ],
    allergens: ['oeufs', 'fruits à coque'],
    preparationTime: 6,
  },
  {
    name: 'Expresso Martini',
    description: "Vodka, liqueur de café, shot d'espresso, simple sirop",
    price: 11,
    mainCategory: 'drinks',
    subCategory: 'cocktail',
    ingredients: ['vodka', 'liqueur de café', 'espresso', 'sirop'],
    allergens: [],
    preparationTime: 5,
  },
  {
    name: 'Amaretto Sour',
    description:
      "Amaretto, jus d'orange, citron jaune, simple sirop, blanc d'oeuf",
    price: 10,
    mainCategory: 'drinks',
    subCategory: 'cocktail',
    ingredients: [
      'Amaretto',
      "jus d'orange",
      'citron',
      'sirop',
      "blanc d'oeuf",
    ],
    allergens: ['oeufs', 'fruits à coque'],
    preparationTime: 5,
  },
  {
    name: 'Porn Star Martini',
    description:
      'Vodka, Passoa, sirop de vanille, fruit de la passion, Vouvray pétillant',
    price: 12,
    mainCategory: 'drinks',
    subCategory: 'cocktail',
    ingredients: [
      'vodka',
      'Passoa',
      'sirop vanille',
      'fruit de la passion',
      'Vouvray',
    ],
    allergens: ['sulfites'],
    preparationTime: 5,
  },
  {
    name: 'Negroni Classico',
    description: "Gin, Campari, Vermouth Otto's",
    price: 11,
    mainCategory: 'drinks',
    subCategory: 'cocktail',
    ingredients: ['gin', 'Campari', "Vermouth Otto's"],
    allergens: [],
    preparationTime: 4,
  },
  {
    name: 'Spicy or Not Margarita',
    description:
      "Tequila infusée au piment & gingembre, citron vert, liqueur d'orange, agave",
    price: 10,
    mainCategory: 'drinks',
    subCategory: 'cocktail',
    ingredients: [
      'tequila',
      'piment',
      'gingembre',
      'citron vert',
      'Triple sec',
      'agave',
    ],
    allergens: [],
    preparationTime: 5,
  },
  {
    name: 'Caribbean Mule',
    description: 'Rhum Diplomatico, citron vert, ginger beer',
    price: 11,
    mainCategory: 'drinks',
    subCategory: 'cocktail',
    ingredients: ['Rhum Diplomatico', 'citron vert', 'ginger beer'],
    allergens: [],
    preparationTime: 5,
  },

  // ── TONICS / ALCOOLS ──────────────────────────────────────────────────────

  {
    name: 'Gin Tonic',
    description: 'Gin, Indian tonic Fever Tree, concombre',
    price: 9,
    mainCategory: 'drinks',
    subCategory: 'alcool',
    ingredients: ['gin', 'Indian tonic', 'concombre'],
    allergens: [],
    preparationTime: 3,
  },
  {
    name: 'Suze Tonic',
    description: 'Suze, Indian tonic, orange',
    price: 8.5,
    mainCategory: 'drinks',
    subCategory: 'alcool',
    ingredients: ['Suze', 'Indian tonic', 'orange'],
    allergens: [],
    preparationTime: 3,
  },
  {
    name: 'Vintage Tonic',
    description: 'Chartreuse verte, Indian tonic',
    price: 10,
    mainCategory: 'drinks',
    subCategory: 'alcool',
    ingredients: ['Chartreuse verte', 'Indian tonic'],
    allergens: [],
    preparationTime: 3,
  },

  // ── DIGESTIFS & SPIRITUEUX ────────────────────────────────────────────────

  {
    name: 'Jameson',
    description: 'Whisky irlandais Jameson, 4cl',
    price: 8,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['whisky irlandais'],
    allergens: ['gluten'],
    preparationTime: 2,
  },
  {
    name: 'Nikka Barrel',
    description: 'Whisky japonais Nikka Barrel, 4cl',
    price: 10,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['whisky japonais'],
    allergens: ['gluten'],
    preparationTime: 2,
  },
  {
    name: "Maker's Mark",
    description: "Bourbon Maker's Mark, 4cl",
    price: 9,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['bourbon américain'],
    allergens: ['gluten'],
    preparationTime: 2,
  },
  {
    name: 'Gin Hendricks',
    description: 'Gin Hendricks, 4cl',
    price: 9,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['gin', 'concombre', 'rose'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Rhum 3 Rivières',
    description: 'Rhum agricole 3 Rivières, 4cl',
    price: 8,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['rhum agricole'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Rhum Plantation Dark',
    description: 'Rhum Plantation Dark, 4cl',
    price: 8,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['rhum ambré'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Rhum Diplomatico',
    description: 'Rhum Diplomatico, 4cl',
    price: 9,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['rhum vénézuélien'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Mezcal Vida',
    description: 'Mezcal Vida, 4cl',
    price: 10,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['agave espadín'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Vodka Wyborowa',
    description: 'Vodka Wyborowa, 4cl',
    price: 8,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['vodka polonaise'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Amaretto',
    description: 'Amaretto di Saronno, 4cl',
    price: 8,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ["liqueur d'amande"],
    allergens: ['fruits à coque'],
    preparationTime: 2,
  },
  {
    name: "Bailey's",
    description: "Bailey's Irish Cream, 4cl",
    price: 8,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['crème irlandaise', 'whisky'],
    allergens: ['lait'],
    preparationTime: 2,
  },
  {
    name: 'Get 27',
    description: 'Get 27 menthe, 4cl',
    price: 8,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['liqueur de menthe'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Get 31',
    description: 'Get 31, 4cl',
    price: 8,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['liqueur de menthe forte'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Limoncello',
    description: 'Limoncello artisanal, 4cl',
    price: 9,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['citrons de Sicile', 'alcool', 'sucre'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Armagnac Armin 6 ans',
    description: 'Armagnac Armin vieilli 6 ans, 4cl',
    price: 8,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['eau de vie de raisin'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Cognac Bourgouin',
    description: 'Cognac Bourgouin, 4cl',
    price: 10,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['eau de vie de raisin'],
    allergens: ['sulfites'],
    preparationTime: 2,
  },
  {
    name: 'Calvados 30',
    description: 'Calvados 30, 4cl',
    price: 10,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['eau de vie de pomme'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Calvados 40 X.O.',
    description: 'Calvados 40 X.O., 4cl',
    price: 10,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['eau de vie de pomme vieilli'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Vieille Prune',
    description: 'Eau de vie Vieille Prune, 4cl',
    price: 9,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['eau de vie de prune'],
    allergens: [],
    preparationTime: 2,
  },
  {
    name: 'Chartreuse Verte',
    description: 'Chartreuse Verte, 4cl — 130 plantes aromatiques',
    price: 10,
    mainCategory: 'drinks',
    subCategory: 'digestif',
    ingredients: ['130 plantes aromatiques', 'alcool'],
    allergens: [],
    preparationTime: 2,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SEED
// ─────────────────────────────────────────────────────────────────────────────

async function seed() {
  try {
    console.log('🔌 Connexion à MongoDB...');
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connecté à', MONGODB_URI);

    await MenuItemModel.deleteMany({});
    console.log('🗑️  Collection vidée');

    const result = await MenuItemModel.insertMany(menuItems);
    console.log(`✅ ${result.length} items insérés avec succès`);

    // Résumé par sous-catégorie
    const summary: Record<string, number> = {};
    menuItems.forEach((item) => {
      summary[item.subCategory] = (summary[item.subCategory] || 0) + 1;
    });
    console.log('\n📊 Résumé par sous-catégorie :');
    Object.entries(summary)
      .sort()
      .forEach(([cat, count]) => {
        console.log(`   ${cat.padEnd(15)} : ${count} items`);
      });
  } catch (error) {
    console.error('❌ Erreur lors du seed :', error);
  } finally {
    await mongoose.disconnect();
    console.log('\n🔌 Déconnecté de MongoDB');
  }
}

seed();
